X=MsgBox("Msg",2+32,"Title") 
X=MsgBox("Msg",2+32,"Title") 
X=MsgBox("Msg",2+32,"Title") 
X=MsgBox("Msg",2+32,"Title") 
X=MsgBox("Msg",2+32,"Title") 
X=MsgBox("Msg",2+32,"Title") 
X=MsgBox("Msg",2+32,"Title") 
X=MsgBox("Msg",2+32,"Title") 
